version: '3.8'

services:
  # TaskFlow Development App
  taskflow:
    image: node:20-alpine
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    env_file:
      - .env.local
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    stdin_open: true
    tty: true
    restart: unless-stopped 